### PR TITLE
Extract backends into separate crates

### LINKED ISSUE #7: Fix wasmtime version
The update to wasmtime v19 breaks this crate again as it specifies that any version of wasmtime is supported. Setting explicit lower and upper bounds (that can be updated in path releases if non-breaking) would allow updating dependecies without wasm_runtime_layer sneaking a new wasmtime version in.

### PR DESCRIPTION
**Pull request by juntyr**
This PR extracts the existing backends into three new crates

- `wasmi-runtime-layer`
- `wasmtime-runtime-layer`
- `webassembly-runtime-layer`

which continue to live in this repo. This allows these crates to evolve more independently (and faster) than the core `wasm_runtime_layer` crate and to e.g. publish breaking releases to keep up with wasmtime's fast development without updating `wasm_runtime_layer`.

If this PR is accepted, a new major version 0.4.0 should be published and all of the new crates should require 0.4.0.

Fixes #7 

- [x] Remove backends from the core crate
- [x] Add back Wasmtime backend and enable its tests
- [x] Add back WASMI backend and enable its tests
- [x] Add back web backend and enable its tests

### CODE REVIEW

**Comment by DouglasDwyer** [comment]
Small nitpick - I would prefer that the crates be named using `snake_case` (this keeps things consistent with the main crate name, and also consistent with how the crate names appear in Rust source code). Also, we can probably call the web layer just `web_runtime_layer` since it is browser-specific rather than WASM-specific.

**Comment by DouglasDwyer** [comment]
My apologies, but I won't be able to allocate time to review and merge this for another week or so. Looks good at first glance - I appreciate your hard work :)

**Comment by juntyr** [comment]
> Small nitpick - I would prefer that the crates be named using `snake_case` (this keeps things consistent with the main crate name, and also consistent with how the crate names appear in Rust source code).

Sure, I can definitely rename the crates.

> Also, we can probably call the web layer just `web_runtime_layer` since it is browser-specific rather than WASM-specific.

My reasoning behind the name is to continue to use the runtime’s name, which in browsers is the WebAssembly JS API. Web would work as well, though this backend presumably also works with Node?

We could also go for longer names that have the full suffix, i.e. [wasmi|wasmtime|js]_wasm_runtime_layer. Should backend be used anywhere in the name?

I think so far my own pyodide-webassembly-runtime-layer is the only backend crate, so you can choose any name that suits you.

**Comment by juntyr** [comment]
> My apologies, but I won't be able to allocate time to review and merge this for another week or so. Looks good at first glance - I appreciate your hard work :)

No worries :) Now that I have my own branch of this, I’ll use it during this time and see if I come across any issues.

**Comment by DouglasDwyer** [comment]
> My reasoning behind the name is to continue to use the runtime’s name, which in browsers is the WebAssembly JS API. Web would work as well, though this backend presumably also works with Node?



Actually, something like `js_runtime_layer` is probably even more descriptive, agreed

**Comment by juntyr** [comment]
> > My reasoning behind the name is to continue to use the runtime’s name, which in browsers is the WebAssembly JS API. Web would work as well, though this backend presumably also works with Node?
> 
> Actually, something like `js_runtime_layer` is probably even more descriptive, agreed

Though without context, js_runtime_layer will be quite ambiguous - should it be js_wasm_runtime_layer? Should the other crates then be e.g. wasmi_wasm_runtime_layer? Or do we only add the wasm prefix if the backend does not mention wasm itself?

**Comment by DouglasDwyer** [comment]
It is kind of a weird one. I think your idea of adding `wasm` only if not explicitly mentioned makes sense - so `js_wasm_runtime_layer` then, haha

**Comment by juntyr** [comment]
ping @DouglasDwyer

**Comment by juntyr** [comment]
pong @DouglasDwyer

**Comment by DouglasDwyer** [comment]
Hey @juntyr, sorry for letting this stay open. My own work has taken me back into WASM-land, so I will make an effort to merge this within the week.

**Comment by DouglasDwyer** [comment]
Thank you for your absolutely stellar work! This is a very nice cleanup of the project, and should make it much easier to track dependency versions. I will be making some minor nitpick changes and then will publish everything.

**Comment by DouglasDwyer** [comment]
All crates are now published! I suspect that you should be able to publish a new version of your pyodide crate as well :)

**Comment by juntyr** [comment]
> All crates are now published! I suspect that you should be able to publish a new version of your pyodide crate as well :)

Done :)

[![Latest Version]][crates.io]

[Latest Version]: https://img.shields.io/crates/v/pyodide-webassembly-runtime-layer
[crates.io]: https://crates.io/crates/pyodide-webassembly-runtime-layer

Thank you so much and I'm excited you're back in WASM land again - `wings` is quite a cool idea!

I also submitted #10 and #11 to update the `wasmtime_runtime_layer` to v19 and v20, respectively. Hopefully, we can get those merged (#10 first so I can then rebase #11 on it) and published so that everything is up to date again 🎈

**Pull request merged**
